# 02MIAR - Matemáticas para la Inteligencia Artificial
## Entrega de Ejercicios Evaluables

### por Luis Izaguirre Viera

- email - lsizaguirre@gmail.com

---

NOTA: Este notebook hace de el desarrollo y entrega de los ejercicios evaluables de la asignatura de Matematicas para la Inteligencia Artificial. En este documento solo se incorporan los códigos en Python asociados a los ejercicios planteados y se entrega junto a un documento.pdf anexo donde se desarrollan el resto de ejercicios. 

---

## Segundo ejercicio

Sea $A \in \mathbb R^{3x3}$ la matriz cuadrada dada por
\begin{equation*}
    A = 
    \begin{pmatrix}
        3 & -3 & 2\\
        -4 & 4 & -4\\
        -3 & 3 & -2
    \end{pmatrix}
\end{equation*}

Obténgase cuatro matrices $B \in \mathbb R^{3x3}$ tales que $B^{2} = A$.
Sugerencia: diagonalizar A puede ser de utilidad. Para el proceso de diagonalización, puedes hacer uso de `numpy.linalg.eig` en Python.

### Solución: 

1.- Importamos las librerias necesarias y utilizamos un comando propio de NumPy que nos va a permitir suprimir la notación cientifica a la hora de imprimir valores y configurar una precisión de 5 decimales

In [86]:
import numpy as np

np.set_printoptions(suppress=True, precision=5)

<br/>
2.- Inicializamos la matriz $A$

In [87]:
A = np.array([[3,-3,2], 
              [-4,4,-4], 
              [-3,3,-2]])

<br/>
3. Para buscar una matriz B tal que $B^2 = A$, debemos encontrar los valores propios y los vectores propios

In [88]:
valores_propios, vectores_propios = np.linalg.eig(A) 

print(f'Los valores_propios de A son:\n {valores_propios}\n')
print(f'Los vectores_propios de A son:\n {vectores_propios}')

Los valores_propios de A son:
 [4. 0. 1.]

Los vectores_propios de A son:
 [[-0.57735  0.70711 -0.70711]
 [ 0.57735  0.70711  0.     ]
 [ 0.57735 -0.       0.70711]]


<br/>
Estos valores nos permitiran diagonalizar la matriz $A$ y poder escribirla de la forma $A=PDP^{-1}$ 

Nuestro objetivo es encontrar una matriz $B$, tal que $B^{2}=A$, por lo tanto podemos decir que habra una matriz $B$, tal que $B=PD^{1/2}P^{-1}$

Para ello, primero calculamos $P$ y $P^{-1}$

In [89]:
P = vectores_propios
P_INVERTIDA = np.linalg.inv(P)

print(f'La matriz P es:\n {P}\n')
print(f'La matriz P invertida es:\n {P_INVERTIDA}\n')

La matriz P es:
 [[-0.57735  0.70711 -0.70711]
 [ 0.57735  0.70711  0.     ]
 [ 0.57735 -0.       0.70711]]

La matriz P invertida es:
 [[-1.73205  1.73205 -1.73205]
 [ 1.41421 -0.       1.41421]
 [ 1.41421 -1.41421  2.82843]]



<br/>
Para obtener la matriz diagonal $D$ lo hacemos a partir de los vectores propios.
La matriz diagonal $D$ es:
<br/><br/>

\begin{equation*}
    D = 
    \begin{pmatrix}
        4 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & 1
    \end{pmatrix}
\end{equation*}
\
Lo interesante acá es que
\
\begin{equation*}
    D^{1/2} = 
    \begin{pmatrix}
        \sqrt{4} & 0 & 0\\
        0 & \sqrt{0} & 0\\
        0 & 0 & \sqrt{1}
    \end{pmatrix}
\end{equation*}
\
y esto nos permite construir 4 matrices diagonales para obtener 4 matrices $B$
\begin{equation*}
    D^{1/2}_{1} = 
    \begin{pmatrix}
        2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & 1
    \end{pmatrix}, 
    D^{1/2}_{2} = 
    \begin{pmatrix}
        2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & -1
    \end{pmatrix}, 
    D^{1/2}_{3} = 
    \begin{pmatrix}
        -2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & 1
    \end{pmatrix}, 
    D^{1/2}_{4} = 
    \begin{pmatrix}
        -2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & -1
    \end{pmatrix}
\end{equation*}

<br/>
Primer caso, con:
\begin{equation*}
    D^{1/2}_{1} = 
    \begin{pmatrix}
        2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & 1
    \end{pmatrix}
\end{equation*} 

In [90]:
D_SQRT = np.array([[2, 0, 0], [0, 0, 0], [0, 0, 1]])

B = np.matmul(np.matmul(P,D_SQRT), P_INVERTIDA)
print(f'La matriz B es:\n {B}\n')

BB = np.matmul(B,B)
print(f'La matriz B**2 es:\n {BB}\n')

La matriz B es:
 [[ 1. -1.  0.]
 [-2.  2. -2.]
 [-1.  1. -0.]]

La matriz B**2 es:
 [[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]



<br/>
Segundo caso, con:
\begin{equation*}
    D^{1/2}_{2} = 
    \begin{pmatrix}
        -2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & 1
    \end{pmatrix}
\end{equation*} 

In [91]:
D_SQRT = np.array([[-2, 0, 0], [0, 0, 0], [0, 0, 1]])

B = np.matmul(np.matmul(P,D_SQRT), P_INVERTIDA)
print(f'La matriz B es:\n {B}\n')

BB = np.matmul(B,B)
print(f'La matriz B**2 es:\n {BB}\n')

La matriz B es:
 [[-3.  3. -4.]
 [ 2. -2.  2.]
 [ 3. -3.  4.]]

La matriz B**2 es:
 [[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]



<br/>
Tercer caso, con:
\begin{equation*}
    D^{1/2}_{3} = 
    \begin{pmatrix}
        2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & -1
    \end{pmatrix}
\end{equation*} 

In [92]:
D_SQRT = np.array([[2, 0, 0], [0, 0, 0], [0, 0, -1]])

B = np.matmul(np.matmul(P,D_SQRT), P_INVERTIDA)
print(f'La matriz B es:\n {B}\n')

BB = np.matmul(B,B)
print(f'La matriz B**2 es:\n {BB}\n')

La matriz B es:
 [[ 3. -3.  4.]
 [-2.  2. -2.]
 [-3.  3. -4.]]

La matriz B**2 es:
 [[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]



<br/>
Cuarto caso, con:
\begin{equation*}
    D^{1/2}_{4} = 
    \begin{pmatrix}
        -2 & 0 & 0\\
        0 & 0 & 0\\
        0 & 0 & -1
    \end{pmatrix}
\end{equation*} 

In [93]:
D_SQRT = np.array([[-2, 0, 0], [0, 0, 0], [0, 0, -1]])

B = np.matmul(np.matmul(P,D_SQRT), P_INVERTIDA)
print(f'La matriz B es:\n {B}\n')

BB = np.matmul(B,B)
print(f'La matriz B**2 es:\n {BB}\n')

La matriz B es:
 [[-1.  1. -0.]
 [ 2. -2.  2.]
 [ 1. -1.  0.]]

La matriz B**2 es:
 [[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]



\
En conclusión las cuatro matrices $B \in \mathbb R^{3x3}$ tales que $B^{2} = A$, serian:
<br/><br/>
\begin{equation*}
    B_{1} = 
    \begin{pmatrix}
        1 & -1 & 0\\
        -2 & 2 & -2\\
        -1 & 1 & 0
    \end{pmatrix}, 
    B_{2} = 
    \begin{pmatrix}
        -3 & 3 & -4\\
        -2 & 2 & -2\\
        3 & -3 & 4
    \end{pmatrix}, 
    B_{3} = 
    \begin{pmatrix}
        3 & -3 & 4\\
        -2 & 2 & -2\\
        -3 & 3 & -4
    \end{pmatrix}, 
    B_{4} = 
    \begin{pmatrix}
        -1 & 1 & 0\\
        2 & -2 & 2\\
        1 & -1 & 0
    \end{pmatrix}
\end{equation*}
<br/><br/>

---

## Cuarto ejercicio

Se dispone de tres cartas con las características siguientes:
- La primera carta es roja por ambos lados.
- La segunda carta es verde por ambos lados.
- La tercera carta es roja por un lado y verde por el otro lado.

Se introducen las tres cartas en una bolsa, se barajan y se extrae una carta completamente al azar, poníendola sobre la mesa sin mirar y observando posteriormente el lado que ha quedado visible, el cual ha resultado ser de color verde.

b) Realiza una simulación en Python para este problema, estimando la probabilidad tras realizar una cantidad elevada de simulaciones del problema. La función deberá tener como parámetro de entrada el número de simulaciones n y como parámetro de salida una estimación de la probabilidad p. Para simular la extracción de las cartas y del lado visible tras la extracción puedes valerte de random.randint. Recuerda que durante la simulación sólo deberán contabilizarse los experimentos en los que la cara visible de la carta obtenida ha sido verde y, sobre estos, estimar la proporción de veces en las que la carta de la que procede ha resultado ser la que es verde por ambas caras.

In [94]:
import random

numero_de_simulaciones = 100000 # Nro de simulaciones que se ejecutarán

def simulacion(numero_de_simulaciones):
    contador_de_exitos = 0
    contador_de_experimentos = 0

    # Definición de las cartas
    cartas = [('roja', 'roja'), ('roja', 'verde'), ('verde', 'verde')]

    for _ in range(numero_de_simulaciones):
        # Se elige una carta de las tres posibles
        carta_de_la_bolsa = cartas[random.randint(0,2)]
        
        # De la carta elegida se toma una de las caras
        cara_visible = carta_de_la_bolsa[random.randint(0,1)]

        if cara_visible == 'verde': # Si la cara es verde se cuenta el experimento
            contador_de_experimentos += 1
            if carta_de_la_bolsa == ('verde', 'verde'): # Si la carta es la verde, verde se cuenta como éxito
                contador_de_exitos += 1
    
    # Se imprime la probabilidad, relación de casos de exito entre casos contabilizados (cara visible verde)
    print(contador_de_exitos/contador_de_experimentos) 

simulacion(numero_de_simulaciones)

0.6654387475224729
