# 02MIAR - Matemáticas para la Inteligencia Artificial
## Entrega de Ejercicios Evaluables

### por Luis Izaguirre Viera

- email - lsizaguirre@gmail.com

---

## 1. Demúestrese o refútese razonadamente la equivalencia entre los pares de enunciados siguientes:

### a) Primer par de enunciados:
- $\neg \exists x : \neg(\neg p(x)\lor \neg q(x))$, al que llamaremos primer enunciado
- $[\forall x, \neg p(x)] \lor [\forall x, \neg q(x)]$, al que llamaremos segundo enunciado

1. Para demostrar o refutar su equivalencia partiremos aplicando al primer enunciado la siguiente ley de Morgan:

- Ley: $\forall x,  p(x) \equiv \neg [\exists x : \neg p(x)]$

2. De esa forma el primer enunciado $\neg \exists x : \neg(\neg p(x)\lor \neg q(x))$, podriamos tambien escribirlo así:

- primer enunciado $\forall x : \neg p(x) \lor \neg q(x)$

3. Además sabemos que existe una propiedad de la equivalencia que nos dice: 

- Propiedad: $[\forall x, p(x)] \lor [\forall x, q(x)] \models \forall x : [p(x) \lor q(x)]$

4. Tomando esto último en consideración podriamos aplicarlo al primer enunciado y quedaría demostrado que: 

- $[\forall x, \neg p(x)] \lor [\forall x, \neg q(x)] \models \forall x : [\neg p(x) \lor \neg q(x)]$

5. Por esto último podemos concluir que el segundo enunciado implica al primero, pero no en sentido contrario, por lo tanto:
 
- #### NO son equivalentes ####

### a) Segundo par de enunciados:
- $\neg ( \forall x, \exists y: [ (p(x,y) \land q(x,y)) \implies r(x,y) ] )$, al que llamaremos primer enunciado
- $\exists x : [(\forall y, p(x,y)) \land (\forall y, q(x,y)) \land (\forall y, \neg r(x,y))]$, al que llamaremos segundo enunciado

1. Analizando inicialmente ambos enunciados decido partir por el segundo, intentando resolver primero la parte interna del mismo. A esta parte la llamaremos AUX, de esta forma podriamos reescribir el segundo enunciado como: 
- segundo enunciado: $\exists x :$ AUX,
- donde AUX = $[(\forall y, p(x,y)) \land (\forall y, q(x,y)) \land (\forall y, \neg r(x,y))]$

2. Ahora nos concentraremos en simplificar AUX y para ello aplicaremos la siguiente propiedad

- Propiedad: $[\forall x, p(x)] \land [\forall x, q(x)] \equiv \forall x : [p(x) \land q(x)]$

3. Aplicando lo anterior sobre AUX = $[(\forall y, p(x,y)) \land (\forall y, q(x,y)) \land (\forall y, \neg r(x,y))]$, nos quedaría de la siguiente forma:

- AUX = $\forall y, [p(x,y)) \land q(x,y) \land \neg r(x,y)]$

3. Además sabemos que existe una ley de Morgan que nos dice:

- Ley: $\forall x,  p(x) \equiv \neg [\exists x : \neg p(x)]$ 

4. Si aplicamos esta ley sobre AUX, tendriamos: 

- AUX = $\neg \exists y, \neg [p(x,y)) \land q(x,y) \land \neg r(x,y)]$

5. Tambien sabemos que:

- $a \land (b \land c) \equiv (a \land b) \land c$
y que 
- $\neg (a \land b) \equiv \neg a \lor \neg b$

6. Si consideramos:
- a= $p(x,y)) \land q(x,y)$
- b= $\neg r(x,y)$

7. Podriamos perfectamente reescribir AUX como:
- AUX = $\neg \exists y, [\neg (p(x,y)) \land q(x,y)) \lor \neg(\neg r(x,y))]$
o lo que es lo mismo.
- AUX = $\neg \exists y, [\neg (p(x,y)) \land q(x,y)) \lor r(x,y)]$

8. Para finalizar con la manipulacioón de AUX, tambien recordemos que $\neg p \lor q \equiv p \implies q$, y aplicando esto sobre AUX quedaría de la siguiente forma:
- AUX = $\neg \exists y, [(p(x,y)) \land q(x,y)) \implies r(x,y)]$

9. Ahora podemos sustituir AUX en su original, es decir, en el segundo enunciado:
- segundo enunciado: $\exists x :$ AUX,
- segundo enunciado: $\exists x : \neg \exists y, [(p(x,y)) \land q(x,y)) \implies r(x,y)]$,

10. Para finalizar, aplicaremos sobre el cuantificador existencial de x la siguiente ley:
- Ley: $\exists x : p(x) \equiv \neg[\forall x, \neg p(x)]$

11. Quedando el segundo enunciado reescrito de la siguiente forma:
$\neg ( \forall x, \exists y: [ (p(x,y) \land q(x,y)) \implies r(x,y) ] )$

lo que es igual al primer enunciado, por lo tanto estos dos enunciados **SON EQUIVALENTES**


---

## 4. Se dispone de tres cartas con las características siguientes:
- La primera carta es roja por ambos lados.
- La segunda carta es verde por ambos lados.
- La tercera carta es roja por un lado y verde por el otro lado.

Se introducen las tres cartas en una bolsa, se barajan y se extrae una carta completamente al azar, poníendola sobre la mesa sin mirar y observando posteriormente el lado que ha quedado visible, el cual ha resultado ser de color verde.

### a) Intuitivamente, ¿cúal crees que es la probabilidad de que al girar la carta el otro lado resulte ser tambíen verde?

Lo habitual sería responder que la probabilidad es 0.5. La primera intuición nos hace pensar que si el ladovisible de la carta seleccionada es de color verde, descartariamos una de las opciones iniciales (la que es roja por ambos lados) y nuestras probabilidades se centrarían en 2.

Una opción de 2.

### b) Realiza una simulación en Python para este problema, estimando la probabilidad tras realizar una cantidad elevada de simulaciones del problema. La función deberá tener como parámetro de entrada el número de simulaciones n y como parámetro de salida una estimación de la probabilidad p. Para simular la extracción de las cartas y del lado visible tras la extracción puedes valerte de random.randint. Recuerda que durante la simulación sólo deberán contabilizarse los experimentos en los que la cara visible de la carta obtenida ha sido verde y, sobre estos, estimar la proporción de veces en las que la carta de la que procede ha resultado ser la que es verde por ambas caras.



In [71]:
import random

numero_de_simulaciones = 100000

def simulacion(numero_de_simulaciones):
    contador_de_exitos = 0
    contador_de_experimentos = 0

    cartas = [('roja', 'roja'), ('roja', 'verde'), ('verde', 'verde')]

    for _ in range(numero_de_simulaciones):
        carta_de_la_bolsa = cartas[random.randint(0,2)]
        cara_visible = carta_de_la_bolsa[random.randint(0,1)]

        #print(carta_de_la_bolsa)
        #print(cara_visible)

        if cara_visible == 'verde':
            contador_de_experimentos += 1
            if carta_de_la_bolsa == ('verde', 'verde'):
                contador_de_exitos += 1
    
    print(contador_de_exitos/contador_de_experimentos)

simulacion(numero_de_simulaciones)

0.6639668826493881


### c) ¿Son los resultados obtenidos consistentes con tu intuiciòn inicial? De no ser el caso, ¿puedes conjeturar el valor correcto de la probabilidad? Una vez realizada, demuestra formalmente que el valor de la probabilidad conjeturada es el correcto y/o porporciona esquemáticamente la explicación de por qué se verifica.

La simulación evidencia una probabilidad de 2/3 o 0,666666.

Generalmente por intuición descartamos información con la que ya contamos y en este caso es que hay un suceso inicial. Este es un típico ejemplo de Probabilidad Condicionada, donde tenemos que:

P(de que la carta sea la verde, verde) = P(vv) = 1/3, una de tres cartas posibles.
P(de que el lado visible de la primera carta sea verde) = P(cv) = 3/6 = 1/2, tres opciones de 6 posibles.
P(vv y cv)

A= PDP-1
A2 = (PDP-1)(PDP-1)
A2 = PD(P-1P)DP-1
A2 = PD(I)(D)P-1
A2 = PD(D)P-1
A2 = P D2 P-1

Para diagonalizar una matriz. 
1 Calcular los valores propios
2 Calcular vectores propios asociados
3 Formar las matrices P y D

In [23]:
import numpy as np
matrix_aux = [[3,-3,2], [-4,4,-4], [-3,3,-2]]
#matrix_aux = [[7, -10], [5,-8]]
m = np.array(matrix_aux)

v, w = np.linalg.eig(m) 

np.set_printoptions(suppress=True)
print(v)
print(w)

[4. 0. 1.]
[[-0.57735027  0.70710678 -0.70710678]
 [ 0.57735027  0.70710678  0.        ]
 [ 0.57735027 -0.          0.70710678]]


In [ ]:
factorizar\:\left(3-x\right)\left[\left(4-x\right)\left(-2-x\right)+12\right]+3\left[-4\left(-2-x\right)-12\right]+2\left[-12-\left(-3\right)\left(4-x\right)\right]\:

In [2]:
import numpy as np
matrix_aux = [[3,-3,2], [-4,4,-4], [-3,3,-2]]

m = np.array(matrix_aux)

v = np.sqrt(m) 

np.set_printoptions(suppress=True)
print(v)


[[1.73205081        nan 1.41421356]
 [       nan 2.                nan]
 [       nan 1.73205081        nan]]


<ipython-input-2-d3a0df2a5142>:6: RuntimeWarning: invalid value encountered in sqrt
  v = np.sqrt(m)


In [17]:
A = np.array([[2, 0], [0, 3]])
B = np.linalg.matrix_power(A, 2)

print(A)
print(B)

[[2 0]
 [0 3]]
[[4 0]
 [0 9]]


In [19]:
from scipy.linalg import sqrtm
a = np.array([[4, 0], [0, 9]])
r = sqrtm(a)
r

array([[2., 0.],
       [0., 3.]])

In [20]:
A = np.array([[3, -1], [-2, 4]])
B = np.linalg.matrix_power(A, 2)

print(A)
print(B)

[[ 3 -1]
 [-2  4]]
[[ 11  -7]
 [-14  18]]


In [77]:
# importing Numpy package
import numpy as np
  
# creating a 3X3 Numpy matrix
n_array = np.array([[3, -3, 2], [-4, 4, -4], [-3, 3, -2]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
valores_propios, vectores_propios = np.linalg.eig(n_array)
  
print("\nValores propios:")
print(valores_propios)

print("\nVectores propios:")
print(vectores_propios)

P = vectores_propios
D = np.diag([2,0,1])
PI = np.linalg.inv(P)

B = np.matmul(np.matmul(P,D), PI)
print("\n Matriz B")
print(B)

BB = np.matmul(B,B)
print("\n Matriz B**2")
print(BB)

P = np.array([[5, -2, -3], [5, 2, 0], [0, 2, 3]])
print(P)
D = np.diag([0,-2,-1])
PI = np.linalg.inv(P)

B = np.matmul(np.matmul(P,D), PI)
print("\n Matriz B")
print(B)

BB = np.matmul(B,B)
print("\n Matriz B**2")
print(BB)


print(Jugar con la diagonal)

Numpy Matrix is:
[[ 3 -3  2]
 [-4  4 -4]
 [-3  3 -2]]

Valores propios:
[4. 0. 1.]

Vectores propios:
[[-0.57735027  0.70710678 -0.70710678]
 [ 0.57735027  0.70710678  0.        ]
 [ 0.57735027 -0.          0.70710678]]

 Matriz B
[[ 1. -1.  0.]
 [-2.  2. -2.]
 [-1.  1. -0.]]

 Matriz B**2
[[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]
[[ 5 -2 -3]
 [ 5  2  0]
 [ 0  2  3]]

 Matriz B
[[-1.  1.  0.]
 [ 2. -2.  2.]
 [ 1. -1.  0.]]

 Matriz B**2
[[ 3. -3.  2.]
 [-4.  4. -4.]
 [-3.  3. -2.]]
